#!/usr/bin/env python3
"""Build MJCF variants of Microduck that have a real ankle-roll DOF per leg.

`scripts/hw_tradeoff.py` ranks hardware options from static geometry. That is not
enough to claim anything about agility, so this script produces an actual robot:
a 16-servo Microduck with a second hinge under each ankle, an actuator driving
it, the roll bracket's mass and inertia, and keyframes resized for the new joints.
`scripts/ankle_roll_sim.py` then runs both robots through the same physics tests.

Two variants, because how the servo is mounted is most of the cost:

    coincident  roll axis THROUGH the ankle pitch axis (side-mounted servo).
                Best case: no extra leg length, only mass.
    serial      roll servo stacked UNDER the pitch servo, the way a naive
                bracket redesign would do it: the sole drops by `--stack` mm,
                so the leg gets longer and the CoM rises.

The roll axis is the robot's fore-aft direction expressed in the ankle body
frame, orthogonalised against the pitch axis, so `ankle_roll = 0` reproduces the
baseline robot exactly (checked by `ankle_roll_sim.py`'s parity test).

    uv run python scripts/ankle_roll_variant.py            # writes both variants
"""

from __future__ import annotations

import argparse
import xml.etree.ElementTree as ET
from pathlib import Path

import mujoco
import numpy as np

ROBOT_DIR = Path(__file__).resolve().parents[1] / "src/mjlab_microduck/robot/microduck"
SIDES = ("left", "right")

# XL330-M288 + printed bracket: 20 x 34 x 26 mm envelope, servo 18 g, bracket 2 g.
ROLL_SERVO_MASS = 0.020
ROLL_SERVO_BOX = (0.020, 0.034, 0.026)
ROLL_RANGE = 0.5236  # +/- 30 deg, covers the hip-roll range it has to cooperate with

GENERATED_HEADER = (
    " GENERATED by scripts/ankle_roll_variant.py from {base} -- do not edit by hand. "
)


def box_inertia(
    mass: float, dims: tuple[float, float, float]
) -> tuple[float, float, float]:
    a, b, c = dims
    return (
        mass / 12.0 * (b * b + c * c),
        mass / 12.0 * (a * a + c * c),
        mass / 12.0 * (a * a + b * b),
    )


def ankle_frames(robot_xml: Path) -> dict[str, dict[str, np.ndarray]]:
    """Fore-aft and down directions in each ankle body frame, measured on the model.

    Taken at the all-zero pose, where the robot faces +x and gravity is -z, so the
    ankle-roll axis is a body-fixed direction that coincides with fore-aft when the
    leg is straight.
    """
    model = mujoco.MjModel.from_xml_path(str(robot_xml))
    data = mujoco.MjData(model)
    mujoco.mj_kinematics(model, data)
    out = {}
    for side in SIDES:
        bid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, f"ankle_{side}")
        rot = data.xmat[bid].reshape(3, 3)
        fwd = rot.T @ np.array([1.0, 0.0, 0.0])
        down = rot.T @ np.array([0.0, 0.0, -1.0])
        # The pitch joint spins about local z; the roll axis must be perpendicular to it.
        fwd[2] = 0.0
        out[side] = {"fwd": fwd / np.linalg.norm(fwd), "down": down}
    return out


def fmt(vec: np.ndarray) -> str:
    return " ".join(f"{v:.9g}" for v in vec)


def split_ankle(
    body: ET.Element, side: str, frame: dict[str, np.ndarray], stack: float
) -> None:
    """Move the foot into a child body hinged about the roll axis."""
    pitch_joint = body.find("joint")
    assert pitch_joint is not None and pitch_joint.get("name") == f"{side}_ankle"
    inertial = body.find("inertial")
    assert inertial is not None

    foot = ET.Element(
        "body",
        {"name": f"foot_{side}", "pos": fmt(stack * frame["down"]), "quat": "1 0 0 0"},
    )
    ET.SubElement(
        foot,
        "joint",
        {
            "axis": fmt(frame["fwd"]),
            "name": f"{side}_ankle_roll",
            "type": "hinge",
            "range": f"{-ROLL_RANGE:.9g} {ROLL_RANGE:.9g}",
            "class": "chosen_actuator",
        },
    )

    # Everything below the pitch servo rides on the roll joint; the ankle body keeps
    # only the roll servo and its bracket.
    for child in list(body):
        if child is pitch_joint:
            continue
        body.remove(child)
        foot.append(child)

    ixx, iyy, izz = box_inertia(ROLL_SERVO_MASS, ROLL_SERVO_BOX)
    bracket = ET.Element(
        "inertial",
        {
            "pos": fmt(0.5 * stack * frame["down"]),
            "mass": f"{ROLL_SERVO_MASS:.9g}",
            "fullinertia": f"{ixx:.6g} {iyy:.6g} {izz:.6g} 0 0 0",
        },
    )
    body.append(bracket)
    # Visual-only stand-in for the added servo, so renders show where it sits.
    # `chosen_actuator` zeroes contype/conaffinity, so it never collides.
    body.append(
        ET.Element(
            "geom",
            {
                "class": "chosen_actuator",
                "name": f"{side}_ankle_roll_servo",
                "type": "box",
                "pos": fmt(0.5 * stack * frame["down"]),
                "size": fmt(0.5 * np.array(ROLL_SERVO_BOX)),
                "rgba": "0.85 0.15 0.15 1",
                "mass": "0",
            },
        )
    )
    body.append(foot)


def add_actuators(root: ET.Element) -> None:
    actuator = root.find("actuator")
    assert actuator is not None
    for side in SIDES:
        idx = next(
            i for i, el in enumerate(actuator) if el.get("name") == f"{side}_ankle"
        )
        actuator.insert(
            idx + 1,
            ET.Element(
                "position",
                {
                    "class": "chosen_actuator",
                    "name": f"{side}_ankle_roll",
                    "joint": f"{side}_ankle_roll",
                },
            ),
        )


def build_robot(base: Path, out: Path, stack: float) -> None:
    frames = ankle_frames(base)
    tree = ET.parse(base)
    root = tree.getroot()
    for side in SIDES:
        body = next(b for b in root.iter("body") if b.get("name") == f"ankle_{side}")
        split_ankle(body, side, frames[side], stack)
    add_actuators(root)
    ET.indent(tree, space="  ")
    root.insert(0, ET.Comment(GENERATED_HEADER.format(base=base.name)))
    tree.write(out, encoding="unicode", xml_declaration=True)


def insert_positions(base_robot: Path) -> tuple[list[int], list[int]]:
    """Where a zero has to appear in every keyframe's qpos and ctrl arrays."""
    model = mujoco.MjModel.from_xml_path(str(base_robot))
    names = [
        mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_JOINT, j)
        for j in range(model.njnt)
    ]
    hinges = [n for n in names if n is not None and n != "trunk_base_freejoint"]
    qpos, ctrl = [], []
    for shift, side in enumerate(SIDES):
        at = hinges.index(f"{side}_ankle") + 1
        qpos.append(7 + at + shift)  # 7 = free joint, shift = zeros inserted before
        ctrl.append(at + shift)
    return qpos, ctrl


def build_scene(
    base_scene: Path, base_robot: Path, out: Path, robot_out: Path, stack: float
) -> None:
    qpos_at, ctrl_at = insert_positions(base_robot)
    tree = ET.parse(base_scene)
    root = tree.getroot()
    include = root.find("include")
    assert include is not None
    include.set("file", robot_out.name)
    for key in root.iter("key"):
        for attr, positions in (("qpos", qpos_at), ("ctrl", ctrl_at)):
            raw = key.get(attr)
            if raw is None:
                continue
            values = raw.split()
            for at in positions:
                values.insert(at, "0")
            if attr == "qpos" and stack:
                # The soles now sit `stack` lower in the body frame; without this the
                # keyframe spawns the robot inside the floor.
                values[2] = f"{float(values[2]) + stack:.9g}"
            key.set(attr, " ".join(values))
    ET.indent(tree, space="  ")
    root.insert(0, ET.Comment(GENERATED_HEADER.format(base=base_scene.name)))
    tree.write(out, encoding="unicode", xml_declaration=True)


VARIANTS = {"coincident": 0.0, "serial": 0.018}


def build(variant: str, robot_stem: str, scene_stem: str, stack: float) -> Path:
    base_robot = ROBOT_DIR / f"{robot_stem}.xml"
    base_scene = ROBOT_DIR / f"{scene_stem}.xml"
    robot_out = ROBOT_DIR / f"{robot_stem}_ankleroll_{variant}.xml"
    scene_out = ROBOT_DIR / f"{scene_stem}_ankleroll_{variant}.xml"
    build_robot(base_robot, robot_out, stack)
    build_scene(base_scene, base_robot, scene_out, robot_out, stack)
    model = mujoco.MjModel.from_xml_path(str(scene_out))
    print(
        f"{scene_out.name}: nu={model.nu} njnt={model.njnt} "
        f"mass={model.body_subtreemass[1]:.4f} kg stack={stack * 1000:.0f} mm"
    )
    return scene_out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--robot", default="robot_walk", help="base robot xml stem")
    ap.add_argument("--scene", default="scene_walk", help="base scene xml stem")
    ap.add_argument("--stack", type=float, default=VARIANTS["serial"])
    args = ap.parse_args()
    for variant, stack in (("coincident", 0.0), ("serial", args.stack)):
        build(variant, args.robot, args.scene, stack)


if __name__ == "__main__":
    main()
