#!/usr/bin/env python3
"""Build the three E5 ankle-roll MJCF variants from either robot family.

The CAD meshes are generated by ``e5_ankle_cad.py`` and are attached at zero
offset in their parent body's frame.  Running this script again rewrites the
same XML bytes, including keyframe padding and generated-file headers.
"""

from __future__ import annotations

import argparse
import math
import xml.etree.ElementTree as ET
from pathlib import Path

import mujoco
import numpy as np
import trimesh
from e5_ankle_cad import (
    ASSET_DIR,
    HARDWARE_MASS_KG,
    PLA_DENSITY_G_CM3,
    ROBOT_DIR,
    SERVO_MASS_KG,
    SERVO_OFFSET_LOCAL_MM,
)

SIDES = ("left", "right")
VARIANTS = ("direct", "remote", "remote_sole")
ROLL_AXIS = {"left": "-1 0 0", "right": "1 0 0"}
PIVOT_MM = {"direct": 0.0, "remote": -12.0, "remote_sole": -12.0}
ROLL_RANGE = {
    "direct": math.radians(30.0),
    "remote": math.radians(45.0),
    "remote_sole": math.radians(45.0),
}
GENERATED_HEADER = (
    " GENERATED by scripts/e5_variant.py from {base} -- do not edit by hand. "
)
E5_MECHANISM_RGBA = "0.95 0.45 0.1 1"


def _fmt(values: np.ndarray | list[float] | tuple[float, ...]) -> str:
    return " ".join(f"{float(value):.9g}" for value in values)


def _mesh_properties(
    mesh_name: str, mass_kg: float | None = None
) -> tuple[np.ndarray, float, np.ndarray]:
    mesh = trimesh.load_mesh(ASSET_DIR / f"{mesh_name}.stl", process=True)
    volume = abs(float(mesh.volume))
    if mass_kg is None:
        mass_kg = volume * PLA_DENSITY_G_CM3 * 1000.0
    inertia = np.asarray(mesh.moment_inertia, dtype=float) / volume * mass_kg
    return np.asarray(mesh.center_mass, dtype=float), mass_kg, inertia


def _inertial(mesh_name: str, mass_kg: float | None = None) -> ET.Element:
    center, mass, inertia = _mesh_properties(mesh_name, mass_kg)
    return ET.Element(
        "inertial",
        {
            "pos": _fmt(center),
            "mass": f"{mass:.9g}",
            "fullinertia": _fmt(
                [
                    inertia[0, 0],
                    inertia[1, 1],
                    inertia[2, 2],
                    inertia[0, 1],
                    inertia[0, 2],
                    inertia[1, 2],
                ]
            ),
        },
    )


def _part_body(
    name: str,
    mesh_name: str,
    parent: ET.Element,
    mass_kg: float | None = None,
    pos: np.ndarray | None = None,
) -> ET.Element:
    body = ET.SubElement(
        parent,
        "body",
        {"name": name, "pos": _fmt(pos) if pos is not None else "0 0 0"},
    )
    body.append(_inertial(mesh_name, mass_kg))
    ET.SubElement(
        body,
        "geom",
        {
            "type": "mesh",
            "class": "self_collision_only",
            "name": f"{name}_geom",
            "mesh": mesh_name,
            "pos": "0 0 0",
            "rgba": E5_MECHANISM_RGBA,
        },
    )
    return body


def _servo_body(
    side: str,
    parent: ET.Element,
    name: str,
    pos: np.ndarray | None = None,
) -> ET.Element:
    body = ET.SubElement(
        parent,
        "body",
        {"name": name, "pos": _fmt(pos) if pos is not None else "0 0 0"},
    )
    body.append(_inertial("xl330", SERVO_MASS_KG))
    ET.SubElement(
        body,
        "geom",
        {
            "type": "mesh",
            "class": "self_collision_only",
            "name": f"{side}_e5_roll_servo",
            "mesh": "xl330",
            "mass": "0",
        },
    )
    return body


def _find_body(root: ET.Element, name: str) -> ET.Element:
    for body in root.iter("body"):
        if body.get("name") == name:
            return body
    raise ValueError(f"body not found: {name}")


def _split_ankle(root: ET.Element, side: str, variant: str) -> ET.Element:
    ankle = _find_body(root, f"ankle_{side}")
    pitch_joint = next(
        child
        for child in ankle
        if child.tag == "joint" and child.get("name") == f"{side}_ankle"
    )
    ankle_children = [child for child in list(ankle) if child is not pitch_joint]
    moved = ankle_children
    if variant == "remote_sole":
        moved = [
            child
            for child in moved
            if not (
                child.tag == "geom"
                and (
                    child.get("mesh") == f"sole_{side}"
                    or child.get("name") == f"{side}_foot_collision"
                )
            )
        ]

    foot = ET.Element(
        "body", {"name": f"foot_{side}", "pos": "0 0 0", "quat": "1 0 0 0"}
    )
    joint_attrs = {
        "name": f"{side}_ankle_roll",
        "type": "hinge",
        "axis": ROLL_AXIS[side],
        "pos": f"0 0 {PIVOT_MM[variant] / 1000.0:.9g}",
        "range": f"{-ROLL_RANGE[variant]:.9g} {ROLL_RANGE[variant]:.9g}",
        "class": "chosen_actuator",
    }
    if variant != "direct":
        joint_attrs.update(
            armature="0.0072",
            damping="0.212",
            frictionloss="0.0096",
        )
    ET.SubElement(foot, "joint", joint_attrs)
    for child in ankle_children:
        ankle.remove(child)
    for child in moved:
        foot.append(child)
    ankle.append(foot)
    return foot


def _add_assets(root: ET.Element) -> None:
    asset = root.find("asset")
    if asset is None:
        raise ValueError("robot XML has no asset section")
    existing = {mesh.get("file") for mesh in asset.findall("mesh")}
    for side in SIDES:
        for part in ("yoke", "footplate", "cradle", "pushrod", "sole"):
            filename = f"e5_{part}_{side}.stl"
            if filename not in existing:
                ET.SubElement(asset, "mesh", {"file": filename})


def _add_new_parts(root: ET.Element, side: str, variant: str, foot: ET.Element) -> None:
    ankle = _find_body(root, f"ankle_{side}")
    _part_body(f"e5_yoke_{side}", f"e5_yoke_{side}", ankle)
    footplate_mass = _mesh_properties(f"e5_footplate_{side}")[1] + HARDWARE_MASS_KG
    _part_body(f"e5_footplate_{side}", f"e5_footplate_{side}", foot, footplate_mass)

    if variant != "direct":
        _part_body(f"e5_pushrod_{side}", f"e5_pushrod_{side}", foot)

    if variant == "remote_sole":
        sole = ET.SubElement(foot, "body", {"name": f"e5_sole_{side}", "pos": "0 0 0"})
        sole.append(_inertial(f"e5_sole_{side}"))
        ET.SubElement(
            sole,
            "geom",
            {
                "type": "mesh",
                "name": f"{side}_foot_collision",
                "class": "collision",
                "mesh": f"e5_sole_{side}",
                "pos": "0 0 0",
            },
        )

    if variant == "direct":
        _servo_body(side, ankle, f"e5_roll_servo_{side}")
    else:
        leg_name = "leg" if side == "left" else "leg_2"
        placement = SERVO_OFFSET_LOCAL_MM[side] / 1000.0
        leg = _find_body(root, leg_name)
        _part_body(
            f"e5_cradle_{side}",
            f"e5_cradle_{side}",
            leg,
            pos=placement,
        )
        _servo_body(side, leg, f"e5_roll_servo_{side}", pos=placement)


def _add_actuators(root: ET.Element, variant: str) -> None:
    actuator = root.find("actuator")
    if actuator is None:
        raise ValueError("robot XML has no actuator section")
    for side in SIDES:
        anchor = next(
            i for i, item in enumerate(actuator) if item.get("name") == f"{side}_ankle"
        )
        attrs = {
            "class": "chosen_actuator",
            "name": f"{side}_ankle_roll",
            "joint": f"{side}_ankle_roll",
        }
        if variant != "direct":
            attrs["gear"] = "2"
        actuator.insert(anchor + 1, ET.Element("position", attrs))


def _add_contact_excludes(root: ET.Element, variant: str) -> None:
    contact = ET.SubElement(root, "contact")
    for side in SIDES:
        leg = "leg" if side == "left" else "leg_2"
        pairs = [
            (f"e5_yoke_{side}", f"ankle_{side}"),
            (f"e5_yoke_{side}", f"e5_footplate_{side}"),
            (f"e5_footplate_{side}", f"ankle_{side}"),
        ]
        if variant != "direct":
            pairs.extend(
                [
                    (f"e5_pushrod_{side}", f"e5_cradle_{side}"),
                    (f"e5_pushrod_{side}", f"e5_roll_servo_{side}"),
                    (f"e5_pushrod_{side}", leg),
                    (f"e5_cradle_{side}", leg),
                ]
            )
        for body1, body2 in pairs:
            ET.SubElement(contact, "exclude", body1=body1, body2=body2)


def _insert_keyframe_padding(root: ET.Element, base_robot: Path) -> None:
    model = mujoco.MjModel.from_xml_path(str(base_robot))
    names = [
        mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_JOINT, i)
        for i in range(model.njnt)
    ]
    hinges = [name for name in names if name and name != "trunk_base_freejoint"]
    qpos_at, ctrl_at = [], []
    for shift, side in enumerate(SIDES):
        at = hinges.index(f"{side}_ankle") + 1
        qpos_at.append(7 + at + shift)
        ctrl_at.append(at + shift)
    for key in root.iter("key"):
        for attr, positions in (("qpos", qpos_at), ("ctrl", ctrl_at)):
            raw = key.get(attr)
            if raw is None:
                continue
            values = raw.split()
            for position in positions:
                values.insert(position, "0")
            key.set(attr, " ".join(values))


def _sole_points(model: mujoco.MjModel, data: mujoco.MjData, side: str) -> np.ndarray:
    gid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_GEOM, f"{side}_foot_collision")
    mesh_id = model.geom_dataid[gid]
    verts = model.mesh_vert[
        model.mesh_vertadr[mesh_id] : model.mesh_vertadr[mesh_id]
        + model.mesh_vertnum[mesh_id]
    ]
    return data.geom_xpos[gid] + verts @ data.geom_xmat[gid].reshape(3, 3).T


def _sole_delta(base: Path, generated: Path, side: str) -> float:
    base_model = mujoco.MjModel.from_xml_path(str(base))
    base_data = mujoco.MjData(base_model)
    key = mujoco.mj_name2id(base_model, mujoco.mjtObj.mjOBJ_KEY, "STAND")
    mujoco.mj_resetDataKeyframe(base_model, base_data, key)
    mujoco.mj_forward(base_model, base_data)
    generated_model = mujoco.MjModel.from_xml_path(str(generated))
    generated_data = mujoco.MjData(generated_model)
    key = mujoco.mj_name2id(generated_model, mujoco.mjtObj.mjOBJ_KEY, "STAND")
    mujoco.mj_resetDataKeyframe(generated_model, generated_data, key)
    mujoco.mj_forward(generated_model, generated_data)
    return float(
        np.linalg.norm(
            _sole_points(base_model, base_data, side).mean(axis=0)
            - _sole_points(generated_model, generated_data, side).mean(axis=0)
        )
    )


def _assert_pushrod_clearance(
    model: mujoco.MjModel, data: mujoco.MjData, side: str
) -> None:
    rod_id = mujoco.mj_name2id(
        model, mujoco.mjtObj.mjOBJ_GEOM, f"e5_pushrod_{side}_geom"
    )
    forbidden = {
        f"leg{'_2' if side == 'right' else ''}",
        f"ankle_{side}",
        f"e5_yoke_{side}",
        f"e5_sole_{side}",
    }
    for contact in data.contact[: data.ncon]:
        if rod_id not in (contact.geom1, contact.geom2):
            continue
        other = contact.geom2 if contact.geom1 == rod_id else contact.geom1
        body = mujoco.mj_id2name(
            model,
            mujoco.mjtObj.mjOBJ_BODY,
            int(model.geom_bodyid[other]),
        )
        mesh_id = int(model.geom_dataid[other])
        mesh = (
            mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_MESH, mesh_id)
            if mesh_id >= 0
            else None
        )
        if body in forbidden or mesh == f"sole_{side}":
            raise AssertionError(
                f"{side} zero-roll pushrod intersects forbidden geometry "
                f"{body}/{mesh or 'geom'}"
            )


def _assert_no_contacts(
    model: mujoco.MjModel, data: mujoco.MjData, pose_name: str
) -> None:
    contacts = [
        (
            mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, int(contact.geom1)),
            mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, int(contact.geom2)),
            float(contact.dist),
        )
        for contact in data.contact[: data.ncon]
    ]
    if contacts:
        raise AssertionError(
            f"{pose_name} has {len(contacts)} contacts: {contacts[:8]}"
        )


def _disable_world_collisions(model: mujoco.MjModel) -> None:
    for geom_id, body_id in enumerate(model.geom_bodyid):
        if body_id == 0:
            model.geom_contype[geom_id] = 0
            model.geom_conaffinity[geom_id] = 0


def _report_remote_gear_mapping(model: mujoco.MjModel, variant: str, side: str) -> None:
    if variant == "direct":
        return
    actuator = mujoco.mj_name2id(
        model, mujoco.mjtObj.mjOBJ_ACTUATOR, f"{side}_ankle_roll"
    )
    joint = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, f"{side}_ankle_roll")
    gear = float(model.actuator_gear[actuator, 0])
    ctrl_min, ctrl_max = model.actuator_ctrlrange[actuator]
    q_min, q_max = ctrl_min / gear, ctrl_max / gear
    intended = model.jnt_range[joint]
    print(
        f"{variant} {side}: gear={gear:g} ctrlrange=({ctrl_min:g}, {ctrl_max:g}) "
        f"-> joint target=({q_min:g}, {q_max:g}) rad; "
        f"intended=({intended[0]:g}, {intended[1]:g}) rad"
    )


def build_variant(
    base_robot: Path, base_scene: Path, variant: str
) -> tuple[Path, Path]:
    robot_out = ROBOT_DIR / f"{base_robot.stem}_e5_{variant}.xml"
    scene_out = ROBOT_DIR / f"{base_scene.stem}_e5_{variant}.xml"
    tree = ET.parse(base_robot)
    root = tree.getroot()
    _add_assets(root)
    for side in SIDES:
        foot = _split_ankle(root, side, variant)
        _add_new_parts(root, side, variant, foot)
    _add_actuators(root, variant)
    _add_contact_excludes(root, variant)
    ET.indent(tree, space="  ")
    root.insert(0, ET.Comment(GENERATED_HEADER.format(base=base_robot.name)))
    tree.write(robot_out, encoding="unicode", xml_declaration=True)

    scene_tree = ET.parse(base_scene)
    scene_root = scene_tree.getroot()
    include = scene_root.find("include")
    if include is None:
        raise ValueError("scene XML has no include")
    include.set("file", robot_out.name)
    _insert_keyframe_padding(scene_root, base_robot)
    ET.indent(scene_tree, space="  ")
    scene_root.insert(0, ET.Comment(GENERATED_HEADER.format(base=base_scene.name)))
    scene_tree.write(scene_out, encoding="unicode", xml_declaration=True)

    model = mujoco.MjModel.from_xml_path(str(scene_out))
    data = mujoco.MjData(model)
    key = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_KEY, "STAND")
    mujoco.mj_resetDataKeyframe(model, data, key)
    mujoco.mj_forward(model, data)
    _assert_no_contacts(model, data, "STAND")
    _disable_world_collisions(model)
    data.qpos[:] = 0.0
    data.qvel[:] = 0.0
    mujoco.mj_forward(model, data)
    _assert_no_contacts(model, data, "all-zero")
    mujoco.mj_resetDataKeyframe(model, data, key)
    mujoco.mj_forward(model, data)
    if variant != "direct":
        for side in SIDES:
            _assert_pushrod_clearance(model, data, side)
            _report_remote_gear_mapping(model, variant, side)
    base_model_path = base_scene
    deltas = [_sole_delta(base_model_path, scene_out, side) for side in SIDES]
    for side, delta in zip(SIDES, deltas):
        if variant in ("direct", "remote") and delta > 0.0005:
            raise AssertionError(f"{variant} {side} sole delta {delta * 1000:.3f} mm")
    print(
        f"{scene_out.name}: variant={variant} nu={model.nu} njnt={model.njnt} "
        f"mass={model.body_subtreemass[1]:.6f} kg "
        f"sole_delta_mm={','.join(f'{delta * 1000:.3f}' for delta in deltas)}"
    )
    return robot_out, scene_out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--robot", default=None, help="base robot stem, e.g. robot_walk"
    )
    parser.add_argument(
        "--scene", default=None, help="base scene stem, e.g. scene_walk"
    )
    args = parser.parse_args()
    pairs = (
        [(args.robot, args.scene)]
        if args.robot or args.scene
        else [("robot_walk", "scene_walk"), ("robot_allcollisions", "scene")]
    )
    for robot_stem, scene_stem in pairs:
        if not robot_stem or not scene_stem:
            parser.error("--robot and --scene must be supplied together")
        for variant in VARIANTS:
            build_variant(
                ROBOT_DIR / f"{robot_stem}.xml",
                ROBOT_DIR / f"{scene_stem}.xml",
                variant,
            )


if __name__ == "__main__":
    main()
